const populateMeasurements = [
  {
    id: 'blood_pressure_sys',
    name: 'Blood Pressure (Systolic)',
    minValue: 80,
    maxValue: 130,
    unit: 'mmHg',
  },
  {
    id: 'blood_pressure_dia',
    name: 'Blood Pressure (Diastolic)',
    minValue: 40,
    maxValue: 90,
    unit: 'mmHg',
  },
  {
    id: 'bmi',
    name: 'BMI',
    minValue: 18.5,
    maxValue: 30,
    unit: 'kg/m2',
  },
  {
    id: 'glucose',
    name: 'Glucose',
    minValue: 60,
    maxValue: 100,
    unit: 'mg/dl',
  },
  {
    id: 'ldl',
    name: 'LDL',
    minValue: 0,
    maxValue: 200,
    unit: 'mg/dl',
  },
  {
    id: 'hdl',
    name: 'HDL',
    minValue: 40,
    maxValue: 60,
    unit: 'mg/dl',
  },
  {
    id: 'tgl',
    name: 'TGL',
    minValue: 0,
    maxValue: 200,
    unit: 'mg/dl',
  },
  {
    id: 'creatinine',
    name: 'Creatinine',
    minValue: 0.6,
    maxValue: 1.2,
    unit: 'mg/dl',
  },
  {
    id: 'sodium',
    name: 'Sodium',
    minValue: 135,
    maxValue: 147,
    unit: 'mEq/L',
  },
  {
    id: 'potassium',
    name: 'Potassium',
    minValue: 3.5,
    maxValue: 5,
    unit: 'mEq/L',
  },
  {
    id: 'proteinuria',
    name: 'Proteinuria',
    minValue: 0,
    maxValue: 300,
    unit: 'mg/day',
  },
  {
    id: 'hemoglobin',
    name: 'Hemoglobin',
    minValue: 13.5,
    maxValue: 17.5,
    unit: 'g/dL',
  },
  {
    id: 'hba1c',
    name: 'HbA1c',
    minValue: 0,
    maxValue: 7,
    unit: '%',
  },
];

export default populateMeasurements;
